artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset: nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone
  local_data_file: artifacts/data_ingestion/
  unzip_dir: artifacts/data_ingestion
  kaggle_username: ishansharma13
